### ISSUE TITLE
license in release .zip?

### ISSUE THREAD

**Issue by pmosetc** [antijingoist/opendyslexic#27]
Hi,
I'm porting this for OpenBSD. Currently (0.9.10 beta), when fetching from the release .zip provided, only the compiled fonts, pdf and a bin folder are included.

This means that the license/documentation does not actually come distributed with the release we would be fetching. Our project prefers to use a static zip where possible, but I can only comply with the license by bypassing the .zip and using the source tree at the same point. Is this just an oversight? (edit: also, is it meant not to have a directory structure?) I can work around it with the tagged tree, or we can wait for a release that adds those in as well.

Thanks for your work, and for making this available for distribution!

**Comment by antijingoist** [comment]
Hi! Thanks for your message. I'll pop the license into the next release.

**Comment by antijingoist** [comment]
updated package script to include license, etc.
