### ISSUE TITLE
OpenDyslexic font does not install on macOS Mojave

### ISSUE THREAD

**Issue by flagsoft** [antijingoist/opendyslexic#30]
**Describe the bug**
OpenDyslexic font does not install on macOS Mojave. Can not add to FontBook. Does not show, no warning or error given.

**To Reproduce**
1. Open FontBook.app on macOS Mojave
2. Click on + to add font
3. Open font
4. no error, no warning, does not show in FontBook, OpenOffice, Keynote.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
- opendyslexic-0.9.10-beta-2019.09.16.zip

** Notes
Yes, I can install other fonts like Segoe UI from Microsoft and it works.

It does nothing with OpenDyslexic fonts... Please help. Can't install (does nothing, it seems to install but does not show, no warnings, no errors), can't use it. Yes I did reboot the machine.

Yes it did worked on an other macOS on the same machine. Everything worked just fine. Can't remember which version it was.

**Comment by flagsoft** [comment]
Solution for macOS Mojave: **Copy** the font files (.otf and .woff) to `/Users/your-login-name/Library/Fonts/` and it works without any reboot.

**Comment by antijingoist** [comment]
Thanks for the solution. Sorry I missed this. I've been head down elsewhere working on this.
From the date, I think i know what the issue was, and it should be fixed.

**Comment by justinclift** [comment]
Just tested this now on macOS Mojave (10.14.6), and the problem looks to be fixed.

Steps to test:

1. Unzip each of the OpenDyslexic download .zip files (creates one new directory for each unzipped archive)
2. Start Font Book
3. Click the + button to add a new font
4. Select the directory with the unzipped font files

These were the fonts tested:

* OpenDyslexic 2
  * Regular
  * Italic
  * Bolt
  * Bold Italic
* OpenDyslexic 2 Alt-A
  * Regular
  * Italic
  * Bolt
  * Bold Italic
* OpenDyslexic Mono
  * Regular
* OpenDyslexic 3
  * Regular
  * Bold

**Comment by antijingoist** [comment]
Thanks!
