### ISSUE TITLE
Image in readme

### ISSUE THREAD

**Issue by runxel** [antijingoist/opendyslexic#38]
Hey there, just a small improvement proposal:
Having a screenshot with some text laid out would be aweseome! :)

Thanks for considering.

**Comment by justinclift** [comment]
@runxel That's a good idea.  Any interest in creating a PR with the image and README.md change? :smile:

**Comment by runxel** [comment]
Sadly I don't have the time at hand rn. :(
But I see you've got a project website meanwhile (I think you didn't back then? 🤔), displaying the font, which is good. 💯

**Comment by justinclift** [comment]
No worries at all @runxel, thanks for taking the time to create the suggestion. :smile:
