### ISSUE TITLE
Cyrillic Support [$50]

### ISSUE THREAD

**Issue by antijingoist** [antijingoist/opendyslexic#6]
"Hello,
How about adding Cyrillic support? Most of the letters are the same as in Latin, you just need to add Г,Д,Ж,З,И,Л,П,Ф,Ц,Ч,Ш,Щ,Ю,Я."
##

**Comment by ralienpp** [comment]
I was wondering if this is really completed, or if I am not using it correctly.

I try to apply the font (v3 beta) in a book of poetry for children, this is a minimal example I compile with `lualatex`

```
\documentclass[12pt]{article}

\usepackage{fontspec}
\setmainfont{OpenDyslexic3}

\usepackage{lipsum}
\begin{document}
Когда я был во втором классе, на одном из уроков мы изучали стихотворение, которое заканчивалось троеточием.

\end{document}
```

However, the resulting document has some missing characters:
![image](https://github.com/antijingoist/opendyslexic/assets/295338/0f1c05e6-08c4-49c6-b8b0-4598afb138fb)
