### ISSUE TITLE
Unable to change color with CSS on webpage

### ISSUE THREAD

**Issue by Polarisation** [antijingoist/opendyslexic#66]
**Describe the bug**
Using the fonts from this repo, I am unable to change color via a `color: ` CSS rule when using on a webpage. The font color is always black. This is the case whether I use the .woff or .woff2 files from this repo with `@font-face`, or the .otf installed locally.

**To Reproduce**
```
@font-face {
    font-family: "OpenDyslexic";
    src: url("/assets/fonts/OpenDyslexic-Regular.woff2") format("woff2"),
      url("/assets/fonts/OpenDyslexic-Regular.woff") format("woff");
}

* {
    font-family: "OpenDyslexic", sans-serif;
   color: #fff; /* should be white but is black */
}
```

**Expected behavior**
Expected to be able to change font color.

On [opendyslexic.org](opendyslexic.org) the font is shown in different colors. It uses a different font file, a .ttf which is not included in this repo.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Browser: Chrome or Firefox
 - Version: latest

**Comment by matiastucci** [comment]
@Polarisation did you find a solution for this? I'm having the same issue

**Comment by Polarisation** [comment]
No but there's some older versions of OpenDyslexic floating around the internet which work. I found a .ttf which worked for me... maybe one of these: https://fontlibrary.org/en/font/opendyslexic

**Comment by antijingoist** [comment]
This was resolved in 2022. I missed this, sorry.
