### ISSUE TITLE
open-dyslexic scaled larger

### ISSUE THREAD

**Issue by InnerPeaceJerryC** [antijingoist/opendyslexic#7]
My mother has macular and reads a Kindle. Open-dyslexic is her favorite font. The problem is she's on the largest font her Kindle will display, and her vision is getting worse. 

If there were a way to make versions the font larger at their base so the would display larger on the screen at the same font size, that would be ideal. I'm thinking maybe scaled 110, 120, and 130% if possible. 

This may violate some official spec for fonts, but it's a hack that could work, and that's more important. If the added height cramps the line spacing, that won't be a problem because we can adjust the line spacing on the Kindle. 

I expect my mother is only one of many who would benefit from this. Something like this on a different font for the original Kindles, and people liked it, but those files don't work on modern Kindles, nor do they use this font.

Thank you for any help you can be on this.

**Comment by antijingoist** [comment]
The typeface will continue as it's current size, but because Amazon now allows custom fonts, email me and I'll look into building a larger-sized version for you.

**Comment by InnerPeaceJerryC** [comment]
That would be so great. She has an HD fire 7th generation now and is on the
biggest size.
