### ISSUE TITLE
This font contains trojans and riskware

### ISSUE THREAD

**Issue by CrownVicPI437** [antijingoist/opendyslexic#73]
I downloaded this font to help with my issues and being a developer and come to find out its loaded with trojans.
![hmmmm](https://user-images.githubusercontent.com/81381958/168737892-c592220e-0bc3-44d8-98f4-68ffb5d57e62.PNG)

**Comment by antijingoist** [comment]
I took the time to read the binary output of the files manually. It's just the font. Screenshot shows you have some infected dll files tho, and that's no something I distribute. 
It's also why I avoid distributing OpenDyslexic as an installer.
I know this is a very delayed response, and I apologize, but such are the times we live in. Hope you got your computer issues squared away.
