### ISSUE TITLE
Turkish letters

### ISSUE THREAD

**Issue by CoskunSunali** [antijingoist/opendyslexic#8]
Hi!

First of all, great job!

I read somewhere that you might add additional letters on demand.

Is it possible that you add the following letters?

Ğ (uppercase)
ğ (lowercase)
İ (uppercase)
Ö (uppercase)
Ü (uppercase)

https://www.dafont.com/open-dyslexic.font?text=%26%23286%3B+%26%23287%3B+%26%23304%3B+%D6+%FC

Your work is really appreciated...

**Comment by antijingoist** [comment]
This is complete.
