### ISSUE TITLE
Issue with pay on gumroad.com/l/OpenDyslexic

### ISSUE THREAD

**Issue by RLFouts** [antijingoist/opendyslexic#80]
I tried to give a little money for the download on the https://antijingoist.gumroad.com/l/OpenDyslexic page - but it would not accept any of my cards - even those I use fine everywhere else. I had to put 0 in to get to the download. I just wanted to let you know you might need to check that it's working.

**Comment by antijingoist** [comment]
No worries. The thought counts. 😁
