### ISSUE TITLE
Characters closer to school handwriting

### ISSUE THREAD

**Issue by Charade-Estel** [antijingoist/opendyslexic#9]
Keep the "b" as it is, please! It is perfect!!! :-)
It is so rare to find "b" that look like the way we now teach children to write them: after going down to trace the stem, we immediately go right to draw the counter, like in cursive writing.

Characters to modify to make it look more like students learn them:
- a (like "q" without the descender)
- y (like "u" with a curly descender like "j" or "g")
- J (with a bar like "T")
- 9 (like a large "q" standing on the baseline)

Note: I speak for Quebec schools, I cannot say if the needs are the same for other countries!
##

**Comment by antijingoist** [comment]
Should be complete.
